name: GitHub Classroom Workflow

on: [push]

# This provides maximum permissions for this workflow.  It would be better to
# provide permissions only for the specific actions that need them (but that requires futher research).
permissions: write-all

jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      - name:  Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      # because this MUST be run in separate contexts we cannot use the autograding action
      # (or we just haven't figured out how to do it yet)
      #      - name: Run unit tests
      #        uses: education/autograding@v1
      - name: Make gradlew executable
        id: gradlew-executable
        run: chmod +x ./gradlew
      - name: TestMortarSize1
        if: always()
        run: ./gradlew testPngSize1
      - name: TestMortarSize2
        if: always()
        run: ./gradlew testPngSize2
      - name: StyleTest
        if: always()
        run: ./gradlew checkstyleMain
      - run: echo "🍏 This job's status is ${{ job.status }}."
        if: always()